import Head from "next/head";
import Hero from "@ui/index/Hero";
import HeroCarrousel from "@ui/index/HeroCarrousel";
import ArtProcess from "@ui/index/ArtProcess";
import Traits from "@ui/index/Traits";

export default function Home() {
  return (
    <>
      <Head>
        <title>SpellPotions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <HeroCarrousel />
      <ArtProcess />
      <Traits />
    </>
  );
}
